version: '3.8'

services:
  kata:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: kata
      MYSQL_USER: kata_user
      MYSQL_PASSWORD: kata_pwd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
